import 'package:calendaroffactory/models/position.dart';
import 'package:calendaroffactory/models/shift.dart';
import 'package:calendaroffactory/models/timetable.dart';
import 'package:calendaroffactory/models/timetable_type.dart';
import 'package:flutter/material.dart';

class Timetables with ChangeNotifier {
  static const colorInDay = const Color(0xFFFFBABA);
  static const colorAfterNight = const Color(0xFFBBFFBA);
  static const colorInNight = const Color(0xFFBACFFF);
  static const colorInEvening = const Color(0xFFF1BAFF);
  static const colorDayOff = const Color(0xFFFFFFFF);

  static final List<Timetable> _timetables = [
    Timetable(
      id: 1,
      type: TimetableType.TWELFTH_30,
      name: '12ч смены',
      defaultName: '12ч смены',
      timetableNumber: "График №30",
      shifts: [
        Shift(
          id: 1,
          timetableId: 1,
          name: 'А',
          defaultName: 'А',
          description: '',
          positions: _twelfth30Positions,
          firstDate: DateTime(2016, 2, 26),
        ),
        Shift(
          id: 2,
          timetableId: 1,
          defaultName: 'В',
          name: 'В',
          description: '',
          positions: _twelfth30Positions,
          firstDate: DateTime(2016, 2, 24),
        ),
        Shift(
          id: 3,
          timetableId: 1,
          defaultName: 'Г',
          name: 'Г',
          description: '',
          positions: _twelfth30Positions,
          firstDate: DateTime(2016, 2, 22),
        ),
        Shift(
          id: 4,
          timetableId: 1,
          defaultName: 'Б',
          name: 'Б',
          description: '',
          positions: _twelfth30Positions,
          firstDate: DateTime(2016, 2, 20),
        ),
      ],
    ),
    Timetable(
      id: 2,
      type: TimetableType.EIGHT_4,
      name: '8ч смены',
      defaultName: '8ч смены',
      timetableNumber: "График №4",
      shifts: [
        Shift(
          id: 5,
          timetableId: 2,
          defaultName: 'А',
          name: 'А',
          description: '',
          positions: _eight4Positions,
          firstDate: DateTime(2016, 2, 20),
        ),
        Shift(
          id: 6,
          timetableId: 2,
          defaultName: 'Б',
          name: 'Б',
          description: '',
          positions: _eight4Positions,
          firstDate: DateTime(2016, 2, 28),
        ),
        Shift(
          id: 7,
          timetableId: 2,
          defaultName: 'В',
          name: 'В',
          description: '',
          positions: _eight4Positions,
          firstDate: DateTime(2016, 2, 26),
        ),
        Shift(
          id: 8,
          timetableId: 2,
          defaultName: 'Г',
          name: 'Г',
          description: '',
          positions: _eight4Positions,
          firstDate: DateTime(2016, 2, 24),
        ),
        Shift(
          id: 9,
          timetableId: 2,
          defaultName: 'Д',
          name: 'Д',
          description: '',
          positions: _eight4Positions,
          firstDate: DateTime(2016, 2, 22),
        ),
      ],
    ),
    Timetable(
      id: 3,
      type: TimetableType.DAY_15,
      name: '2 через 2',
      defaultName: '2 через 2',
      timetableNumber: "График №15",
      shifts: [
        Shift(
          id: 10,
          timetableId: 3,
          defaultName: '1 бригада',
          name: '1 бригада',
          description: '',
          positions: _day15Positions,
          firstDate: DateTime(2016, 2, 22),
        ),
        Shift(
          id: 11,
          timetableId: 3,
          defaultName: '2 бригада',
          name: '2 бригада',
          description: '',
          positions: _day15Positions,
          firstDate: DateTime(2016, 2, 20),
        ),
      ],
    ),
  ];

  List<Timetable> get timetables => [..._timetables];

  static Timetable findByType(TimetableType type) {
    return _timetables.firstWhere((pr) => pr.type == type);
  }

  static List<Position> get _twelfth30Positions => [
        Position(
          id: 1,
          timetableId: 1,
          name: '1-я С УТРА',
          sign: '8',
          color: colorInDay,
          workHours: 12,
          description: 'В день',
          order: 1,
        ),
        Position(
          id: 2,
          timetableId: 1,
          name: '2-я С УТРА',
          sign: '8',
          color: colorInDay,
          workHours: 12,
          description: 'В день',
          order: 2,
        ),
        Position(
          id: 3,
          timetableId: 1,
          name: 'ВЫХОДНОЙ',
          sign: '*',
          color: colorDayOff,
          workHours: 0,
          description: 'Выходной',
          order: 3,
        ),
        Position(
          id: 4,
          timetableId: 1,
          name: 'В НОЧЬ',
          sign: '20',
          color: colorInNight,
          workHours: 4,
          description: 'В ночь',
          order: 4,
        ),
        Position(
          id: 5,
          timetableId: 1,
          name: 'С НОЧИ В НОЧЬ',
          sign: '20',
          color: colorInNight,
          workHours: 12,
          description: 'В ночь',
          order: 5,
        ),
        Position(
          id: 6,
          timetableId: 1,
          name: 'ОТСЫПНОЙ',
          sign: 'О',
          color: colorAfterNight,
          workHours: 8,
          description: 'Отсыпной',
          order: 6,
        ),
        Position(
          id: 7,
          timetableId: 1,
          name: 'ВЫХОДНОЙ',
          sign: '*',
          color: colorDayOff,
          workHours: 0,
          description: 'Выходной',
          order: 7,
        ),
        Position(
          id: 8,
          timetableId: 1,
          name: 'ЗАВТРА С УТРА',
          sign: '*',
          color: colorDayOff,
          workHours: 0,
          description: 'Выходной',
          order: 8,
        ),
      ];

  static List<Position> get _eight4Positions => [
        Position(
          id: 9,
          timetableId: 2,
          name: '1-я НОЧЬ',
          sign: '24',
          color: colorInNight,
          workHours: 0.5,
          description: 'В ночь',
          order: 1,
        ),
        Position(
          id: 10,
          timetableId: 2,
          name: '2-я НОЧЬ',
          sign: '24',
          color: colorInNight,
          workHours: 8.5,
          description: 'В ночь',
          order: 2,
        ),
        Position(
          id: 11,
          timetableId: 2,
          name: 'ОТСЫПНОЙ',
          sign: 'О',
          color: colorAfterNight,
          workHours: 8,
          description: 'Отсыпной',
          order: 3,
        ),
        Position(
          id: 12,
          timetableId: 2,
          name: 'ВЫХОДНОЙ',
          sign: '*',
          color: colorDayOff,
          workHours: 0,
          description: 'Выходной',
          order: 4,
        ),
        Position(
          id: 13,
          timetableId: 2,
          name: 'ВЫХОДНОЙ',
          sign: '*',
          color: colorDayOff,
          workHours: 0,
          description: 'Выходной',
          order: 5,
        ),
        Position(
          id: 14,
          timetableId: 2,
          name: '1-я С 4-х',
          sign: '16',
          color: colorInEvening,
          workHours: 7.5,
          description: 'Вечерняя',
          order: 6,
        ),
        Position(
          id: 15,
          timetableId: 2,
          name: '2-я С 4-х',
          sign: '16',
          color: colorInEvening,
          workHours: 7.5,
          description: 'Вечерняя',
          order: 7,
        ),
        Position(
          id: 16,
          timetableId: 2,
          name: 'ВЫХОДНОЙ',
          sign: '*',
          color: colorDayOff,
          workHours: 0,
          description: 'Выходной',
          order: 8,
        ),
        Position(
          id: 17,
          timetableId: 2,
          name: '1-я С УТРА',
          sign: '8',
          color: colorInDay,
          workHours: 8,
          description: 'С утра',
          order: 9,
        ),
        Position(
          id: 18,
          timetableId: 2,
          name: '2-я С УТРА',
          sign: '8',
          color: colorInDay,
          workHours: 8,
          description: 'С утра',
          order: 10,
        ),
      ];

  static List<Position> get _day15Positions => [
        Position(
          id: 19,
          timetableId: 3,
          name: '2-й ВЫХОДНОЙ',
          sign: '*',
          color: colorDayOff,
          workHours: 0,
          description: 'Выходной',
          order: 1,
        ),
        Position(
          id: 20,
          timetableId: 3,
          name: '1-й ДЕНЬ',
          sign: '8',
          color: colorInDay,
          workHours: 11.25,
          description: 'Рабочий',
          order: 2,
        ),
        Position(
          id: 21,
          timetableId: 3,
          name: '2-й ДЕНЬ',
          sign: '8',
          color: colorInDay,
          workHours: 11.25,
          description: 'Рабочий',
          order: 3,
        ),
        Position(
          id: 22,
          timetableId: 4,
          name: '1-й ВЫХОДНОЙ',
          sign: '*',
          color: colorDayOff,
          workHours: 0,
          description: 'Выходной',
          order: 4,
        ),
      ];
}
